CARDIO_SCHEDULE = [
    {'week': 1, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 1, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 1, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 1, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 1, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 1, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 1, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 1, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 1, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 1, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 2, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 2, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 2, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 2, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 2, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 3, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 3, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 3, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 3, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 3, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 4, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 4, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 4, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 7, 'duration high': 7, 'custom low': 6.2, 'custom high': 6.2},
    {'week': 4, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 4, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 4, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 4, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 7, 'duration high': 7, 'custom low': 6.2, 'custom high': 6.2},
    {'week': 4, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 4, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 4, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 5, 'duration high': 10, 'custom low': 4.4, 'custom high': 8.8},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 5, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 7, 'duration high': 7, 'custom low': 6.2, 'custom high': 6.2},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 7, 'duration high': 7, 'custom low': 6.2, 'custom high': 6.2},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 7, 'duration high': 7, 'custom low': 6.2, 'custom high': 6.2},
    {'week': 5, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 8, 'duration high': 8, 'custom low': 7.0, 'custom high': 7.0},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 8, 'duration high': 8, 'custom low': 7.0, 'custom high': 7.0},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 8, 'duration high': 8, 'custom low': 7.0, 'custom high': 7.0},
    {'week': 5, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 6, 'duration high': 6, 'custom low': 5.3, 'custom high': 5.3},
    {'week': 6, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 5, 'duration low': 2, 'duration high': 2, 'custom low': 1.8, 'custom high': 1.8},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 6, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 6, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 7, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 7, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 11, 'duration high': 11, 'custom low': 9.7, 'custom high': 9.7},
    {'week': 7, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 7, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 11, 'duration high': 11, 'custom low': 9.7, 'custom high': 9.7},
    {'week': 7, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 7, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 12, 'duration high': 12, 'custom low': 10.6, 'custom high': 10.6},
    {'week': 7, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 7, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 12, 'duration high': 12, 'custom low': 10.6, 'custom high': 10.6},
    {'week': 7, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 13, 'duration high': 13, 'custom low': 11.4, 'custom high': 11.4},
    {'week': 8, 'day': 2, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 8, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 13, 'duration high': 13, 'custom low': 11.4, 'custom high': 11.4},
    {'week': 8, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 14, 'duration high': 14, 'custom low': 12.3, 'custom high': 12.3},
    {'week': 8, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 8, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 14, 'duration high': 14, 'custom low': 12.3, 'custom high': 12.3},
    {'week': 8, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 8, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 15, 'duration high': 15, 'custom low': 13.2, 'custom high': 13.2},
    {'week': 8, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 3, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 8, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 4, 'duration low': 15, 'duration high': 15, 'custom low': 13.2, 'custom high': 13.2},
    {'week': 8, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 5, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 9, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 24, 'duration high': 24, 'custom low': 21.1, 'custom high': 21.1},
    {'week': 9, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 9, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 28, 'duration high': 28, 'custom low': 24.6, 'custom high': 24.6},
    {'week': 9, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 10, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 10, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 10, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 10, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 11, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 11, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 6, 'training mode': '1', 'step': 'MSS', 'order': 2, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 11, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 11, 'day': 7, 'training mode': '1', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 12, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 12, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 12, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 12, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 12, 'day': 4, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 12, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 12, 'day': 6, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 12, 'day': 6, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 12, 'day': 6, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 13, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 4, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 4, 'training mode': '1', 'step': 'MSS', 'order': 2, 'duration low': 25, 'duration high': 25, 'custom low': 22.0, 'custom high': 22.0},
    {'week': 13, 'day': 4, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 5, 'training mode': '1', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 13, 'day': 7, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 13, 'day': 7, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 13, 'day': 7, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 2, 'training mode': '1', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 2, 'training mode': '1', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 14, 'day': 2, 'training mode': '1', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 4, 'training mode': '2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 4, 'training mode': '2', 'step': 'Base Pace', 'order': 2, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 14, 'day': 4, 'training mode': '2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 6, 'training mode': '2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 14, 'day': 6, 'training mode': '2', 'step': 'Base Pace', 'order': 2, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 14, 'day': 6, 'training mode': '2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 1, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 1, 'training mode': '1, 2', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 15, 'day': 1, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 3, 'training mode': '2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 3, 'training mode': '2', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 15, 'day': 3, 'training mode': '2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 5, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 5, 'training mode': '1, 2', 'step': 'MSS', 'order': 2, 'duration low': 25, 'duration high': 25, 'custom low': 22.0, 'custom high': 22.0},
    {'week': 15, 'day': 5, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 15, 'day': 6, 'training mode': '1', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 16, 'day': 1, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 16, 'day': 1, 'training mode': '1, 2', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 16, 'day': 1, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 16, 'day': 4, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 16, 'day': 4, 'training mode': '1, 2', 'step': 'MSS', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 16, 'day': 4, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 16, 'day': 5, 'training mode': '1', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 16, 'day': 7, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 16, 'day': 7, 'training mode': '1, 2', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 16, 'day': 7, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 3, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 3, 'training mode': '1, 2', 'step': 'MSS', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 17, 'day': 3, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 4, 'training mode': '1', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 17, 'day': 5, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 5, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 17, 'day': 5, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 7, 'training mode': '1, 2', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 17, 'day': 7, 'training mode': '1, 2', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 17, 'day': 7, 'training mode': '1, 2', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 2, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 2, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 18, 'day': 2, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 4, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 4, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 18, 'day': 4, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 6, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 18, 'day': 6, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 18, 'day': 6, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 2, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 2, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 19, 'day': 2, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 4, 'training mode': '3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 4, 'training mode': '3', 'step': 'MSS', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 19, 'day': 4, 'training mode': '3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 5, 'training mode': '2, 3', 'step': 'Recovery', 'order': 1, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 19, 'day': 6, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 19, 'day': 6, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 19, 'day': 6, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 2, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 2, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 20, 'day': 2, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 4, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 4, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 20, 'day': 4, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 5, 'training mode': '3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 5, 'training mode': '3', 'step': 'MSS', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 20, 'day': 5, 'training mode': '3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 6, 'training mode': '2, 3', 'step': 'Recovery', 'order': 1, 'duration low': 25, 'duration high': 25, 'custom low': 22.0, 'custom high': 22.0},
    {'week': 20, 'day': 7, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 20, 'day': 7, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 50, 'duration high': 50, 'custom low': 44.0, 'custom high': 44.0},
    {'week': 20, 'day': 7, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 2, 'training mode': '3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 2, 'training mode': '3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 21, 'day': 2, 'training mode': '3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 4, 'training mode': '2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 4, 'training mode': '2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 21, 'day': 4, 'training mode': '2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 5, 'training mode': '3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 5, 'training mode': '3', 'step': 'MSS', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 21, 'day': 5, 'training mode': '3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 21, 'day': 6, 'training mode': '2, 3', 'step': 'Recovery', 'order': 1, 'duration low': 25, 'duration high': 25, 'custom low': 22.0, 'custom high': 22.0},
    {'week': 22, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 22, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 22, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 22, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 22, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 22, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 23, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 3, 'training mode': '1, 2, 3', 'step': '3 x 1 min Intervals', 'order': 2, 'duration low': 3, 'duration high': 3, 'custom low': 2.6, 'custom high': 2.6},
    {'week': 23, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 23, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 23, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 23, 'day': 6, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 23, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 24, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 3, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 35, 'duration high': 35, 'custom low': 30.8, 'custom high': 30.8},
    {'week': 24, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 5, 'training mode': '1, 2, 3', 'step': '4 x 1 min Intervals', 'order': 2, 'duration low': 4, 'duration high': 4, 'custom low': 3.5, 'custom high': 3.5},
    {'week': 24, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 24, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 24, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 24, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 1, 'duration low': 25, 'duration high': 25, 'custom low': 22.0, 'custom high': 22.0},
    {'week': 25, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 25, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 3, 'training mode': '1, 2, 3', 'step': '5 x 1 min Intervals', 'order': 2, 'duration low': 5, 'duration high': 5, 'custom low': 4.4, 'custom high': 4.4},
    {'week': 25, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 25, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 25, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 25, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 25, 'day': 7, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 30, 'duration high': 30, 'custom low': 26.4, 'custom high': 26.4},
    {'week': 25, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 26, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 26, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 26, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 26, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 26, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 2, 'training mode': '1, 2, 3', 'step': '5 x 2 min Intervals', 'order': 2, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 27, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 27, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 27, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 27, 'day': 6, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 27, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 28, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 3, 'training mode': '1, 2, 3', 'step': '5 x 2 min Intervals', 'order': 2, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 28, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 28, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 5, 'training mode': '1, 2, 3', 'step': '5 x 2 min Intervals', 'order': 2, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 28, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 28, 'day': 7, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 28, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 29, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 3, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 29, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 29, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 5, 'training mode': '1, 2, 3', 'step': '5 x 2 min Intervals', 'order': 2, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 29, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 29, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 29, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 30, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 30, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 30, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 30, 'day': 6, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 40, 'duration high': 40, 'custom low': 35.2, 'custom high': 35.2},
    {'week': 30, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 31, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 31, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 4, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 31, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 31, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 7, 'training mode': '1, 2, 3', 'step': '7 x 2 min Intervals', 'order': 2, 'duration low': 14, 'duration high': 14, 'custom low': 12.3, 'custom high': 12.3},
    {'week': 31, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 31, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 32, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 2, 'training mode': '1, 2, 3', 'step': '5 x 3 min Intervals', 'order': 2, 'duration low': 15, 'duration high': 15, 'custom low': 13.2, 'custom high': 13.2},
    {'week': 32, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 32, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 32, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 4, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 32, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 32, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 6, 'training mode': '1, 2, 3', 'step': '5 x 3 min Intervals', 'order': 2, 'duration low': 15, 'duration high': 15, 'custom low': 13.2, 'custom high': 13.2},
    {'week': 32, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 32, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 33, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 33, 'day': 1, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 3, 'training mode': '1, 2, 3', 'step': '10 x 2 min Intervals', 'order': 2, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 33, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Recovery', 'order': 4, 'duration low': 20, 'duration high': 20, 'custom low': 17.6, 'custom high': 17.6},
    {'week': 33, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 33, 'day': 4, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 5, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 33, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 33, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 60, 'duration high': 60, 'custom low': 52.8, 'custom high': 52.8},
    {'week': 33, 'day': 7, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 2, 'training mode': '1, 2, 3', 'step': 'MSS', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 34, 'day': 2, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 34, 'day': 3, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 34, 'day': 5, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Warm Up', 'order': 1, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
    {'week': 34, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Base Pace', 'order': 2, 'duration low': 45, 'duration high': 45, 'custom low': 39.6, 'custom high': 39.6},
    {'week': 34, 'day': 6, 'training mode': '1, 2, 3', 'step': 'Cool Down', 'order': 3, 'duration low': 10, 'duration high': 10, 'custom low': 8.8, 'custom high': 8.8},
]
